name: full_width
timestamp: 1587159481
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1587067649
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-7264: 'System Messages'
  logo:
    logo-1269: 'Logo / Image'
    logo-8108: 'Logo / Image'
  menu:
    menu-8916: Menu
  social:
    social-4912: Social
  position:
    position-position-4734: Aside
    position-position-3949: Sidebar
  content:
    system-content-1587: 'Page Content'
  copyright:
    copyright-6225: Copyright
  totop:
    totop-5566: 'To Top'
  mobile-menu:
    mobile-menu-3391: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-7264: system-messages-7972
    logo-1269: logo-9608
    menu-8916: menu-6409
    social-4912: social-3171
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    footer: footer
    logo-8108: logo-9571
    copyright-6225: copyright-1736
    totop-5566: totop-8670
    offcanvas: offcanvas
    mobile-menu-3391: mobile-menu-5697
