name: home
timestamp: 1587186925
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1587067649
positions:
  aidebar: 'Widget Position'
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  contentcubes:
    contentcubes-7550: Projects
  content:
    system-content-1113: 'Page Content'
  position:
    position-position-7291: 'Widget Position'
  messages:
    system-messages-2116: 'System Messages'
  logo:
    logo-7775: 'Logo / Image'
    logo-8083: 'Logo / Image'
  menu:
    menu-6378: Menu
    menu-9393: 'Footer Menu'
  social:
    social-3579: Social
  copyright:
    copyright-7126: Copyright
  totop:
    totop-1904: 'To Top'
  mobile-menu:
    mobile-menu-3073: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    system-messages-2116: system-messages-7972
    logo-7775: logo-9608
    menu-6378: menu-6409
    social-3579: social-3171
    logo-8083: logo-9571
    copyright-7126: copyright-1736
    menu-9393: menu-1477
    totop-1904: totop-8670
    mobile-menu-3073: mobile-menu-5697
