name: home
timestamp: 1587144510
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1587067649
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-2116: 'System Messages'
  logo:
    logo-7775: 'Logo / Image'
    logo-8083: 'Logo / Image'
  menu:
    menu-6378: Menu
  social:
    social-3579: Social
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  custom:
    custom-5807: Intro
    custom-3119: Features
    custom-7658: 'Customer Testimonials'
    custom-6355: 'Develop CMS themes quickly'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  content:
    system-content-6629: 'Page Content'
  copyright:
    copyright-7126: Copyright
  horizontalmenu:
    horizontalmenu-3458: 'Horizontal Menu'
  totop:
    totop-1904: 'To Top'
  mobile-menu:
    mobile-menu-3073: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-2116: system-messages-7972
    logo-7775: logo-9608
    menu-6378: menu-6409
    social-3579: social-3171
    footer: footer
    logo-8083: logo-9571
    copyright-7126: copyright-1736
    horizontalmenu-3458: horizontalmenu-9034
    totop-1904: totop-8670
    offcanvas: offcanvas
    mobile-menu-3073: mobile-menu-5697
