version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1587067649
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-2455
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-1113
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
  intro:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      class: ''
      nav: disable
      dots: enable
      autoplay: enable
      autoplaySpeed: ''
      items:
        -
          class: ''
          image: 'gantry-media://header/Detroit-Michigan.jpg'
          title: '<img src="gantry-media://2020/04/smile.png" style="width: 250px; margin: auto;">Welcome to my Site!'
          desc: 'Welcome to BrianFreytag.com. Get to learn more about me!'
          link: ''
          linktext: 'Check Out My Resume'
          buttonclass: button-outline
          disable: '0'
          name: Me
        -
          class: ''
          image: 'gantry-media://header/Detroit-Michigan.jpg'
          title: '<img src="gantry-media://2020/04/ultipro.png" style="width:250px; margin: auto;">Ulitpro SDK for PHP (Unofficial)'
          desc: 'Having trouble with Ultipro''s API? This will help!'
          link: 'https://github.com/brianfreytag/ultipro-sdk-php'
          linktext: 'Download Now'
          buttonclass: button-outline
          disable: '0'
          name: Ultipro
