version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1587067649
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-2455
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/:
    -
      - contentcubes-7550
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-1113
      -
        'sidebar 25':
          -
            - position-position-7291
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
  intro:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      class: ''
      nav: enable
      dots: enable
      autoplay: enable
      autoplaySpeed: '10000'
      imageOverlay: enable
      items:
        -
          class: ''
          image: 'gantry-media://header/Detroit-Michigan.jpg'
          title: 'Welcome to BrianFreytag.com'
          desc: "I’m a security-conscience, solution-focused integration specialist, and\nleader of software engineering teams in the creation and maintaining of\nproprietary business systems applications."
          link: 'https://brianfreytag.com/resume'
          linktext: 'Check Out My Resume'
          buttonclass: button-outline
          disable: '0'
          name: Me
        -
          class: ''
          image: 'gantry-media://header/img01.jpg'
          title: Projects
          desc: 'Curious about what I work on? Check out some of my Open Source projects!'
          link: '#projects'
          linktext: 'Check them out'
          buttonclass: button-outline
          disable: '0'
          name: Projects
        -
          class: ''
          image: 'gantry-media://header/Detroit-Michigan.jpg'
          title: 'Ulitpro SDK for PHP (Unofficial)'
          desc: 'Having trouble with Ultipro''s API? This will help!'
          link: 'https://github.com/brianfreytag/ultipro-sdk-php'
          linktext: 'Download Now'
          buttonclass: button-outline
          disable: '0'
          name: Ultipro
        -
          class: ''
          image: 'gantry-media://header/Detroit-Michigan.jpg'
          title: Blog
          desc: 'I write about things. You can read them.'
          link: '#blog-posts-hp'
          linktext: 'Read My Things'
          buttonclass: button-outline
          disable: '0'
          name: Blog
  contentcubes-7550:
    title: Projects
    attributes:
      title: 'Check Out My Projects'
      items:
        -
          image: 'gantry-media://above/ultipro_sdk.png'
          imageposition: left
          label: PHP
          title: 'Ultipro SDK for PHP (Unofficial)'
          tags: {  }
          link: 'https://github.com/brianfreytag/ultipro-sdk-php'
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _blank
          name: 'Ultipro SDK'
        -
          image: 'gantry-media://above/img02.jpeg'
          imageposition: right
          label: PHP
          title: 'PHP Bijective Library'
          tags: {  }
          link: 'https://github.com/brianfreytag/php-bijective'
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _blank
          name: 'PHP Bijective'
    block:
      id: projects
  system-content-1113:
    block:
      id: blog-posts-hp
  position-position-7291:
    title: 'Widget Position'
    attributes:
      key: aidebar
      chrome: ''
