version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1587067649
layout:
  navigation: {  }
  header: {  }
  intro: {  }
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'aside 25': {  }
      -
        'mainbar 50':
          -
            - system-content-1587
          -
            - contentcubes-6917
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  header:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  intro:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  features:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  aside:
    inherit:
      outline: full_width
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
    attributes:
      class: ''
      variations: ''
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: full_width
      include:
        - attributes
        - block
        - children
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  contentcubes-6917:
    title: 'Content Cubes'
    attributes:
      css:
        class: ''
      title: ''
      items:
        -
          image: 'gantry-media://above/ultipro_sdk.png'
          imageposition: left
          label: PHP
          title: 'Ultipro SDK for PHP'
          link: 'https://github.com/brianfreytag/ultipro-sdk-php'
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _blank
          name: 'Ultipro SDK'
        -
          image: 'gantry-media://above/img02.jpeg'
          imageposition: right
          label: PHP
          title: 'PHP Bijective Library'
          link: 'https://github.com/brianfreytag/php-bijective'
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _blank
          name: 'PHP Bijective'
